version: 2.1
orbs:
  python: circleci/python@volatile

jobs:
  run-tests:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run green
  run-mypy:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run mypy
          command: poetry run mypy src
  run-flake8:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run flake8
          command: poetry run flake8 src
  run-lizard:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run lizard
          command: poetry run lizard -T nloc=150 -T length=50 -T parameter_count=10

workflows:
  check-all:
    jobs:
      - run-tests
      - run-mypy
      - run-flake8
      - run-lizard
