version: 2.1
orbs:
  python: circleci/python@volatile

executors:
  py310-executor:
    docker:
      - image: cimg/python:3.10
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: small

jobs:
  run-validator:
    parameters:
      cmd:
        type: string
      params:
        type: string
        default: ""
    executor: py310-executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run << parameters.cmd >>
          command: poetry run << parameters.cmd >> << parameters.params >>
  run-tests:
    executor: py310-executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run green
  run-mypy:
    executor: py310-executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run mypy
          command: poetry run mypy src
  run-flake8:
    executor: py310-executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run flake8
          command: poetry run flake8 src
  run-lizard:
    executor: py310-executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run lizard
          command: poetry run lizard -T nloc=150 -T length=50 -T parameter_count=10
  run-safety:
    executor: py310-executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run safety
          command: poetry run safety check

workflows:
  check-all:
    jobs:
      - run-validator:
          context:
            - Accounts
          cmd: green
      - run-validator:
          context:
            - Accounts
          cmd: mypy
          params: src
      - run-validator:
          context:
            - Accounts
          cmd: flake8
          params: src
      - run-validator:
          context:
            - Accounts
          cmd: lizard
          params: -T nloc=150 -T length=50 -T parameter_count=10
      - run-validator:
          context:
            - Accounts
          cmd: safety
          params: check
